export const REGIONS = [
  { id: "01", name: "Arica y Parinacota" },
  { id: "02", name: "Tarapacá" },
  { id: "03", name: "Antofagasta" },
  { id: "04", name: "Atacama" },
  { id: "05", name: "Coquimbo" },
  { id: "06", name: "Valparaíso" },
  { id: "07", name: "Libertador General Bernardo O'Higgins" },
  { id: "08", name: "Maule" },
  { id: "09", name: "Ñuble" },
  { id: "10", name: "Los Lagos" },
  { id: "11", name: "Aysén del General Carlos Ibáñez del Campo" },
  { id: "12", name: "Magallanes y de la Antártica Chilena" },
  { id: "13", name: "Región Metropolitana de Santiago" },
  { id: "14", name: "Los Ríos" },
  { id: "15", name: "Atacama" },
]

export const COMMUNES_BY_REGION: Record<string, string[]> = {
  "01": ["Arica", "Camarones", "Putre", "General Lagos"],
  "02": ["Iquique", "Alto Hospicio", "Camiña", "Colchane", "Huara", "Pica", "Pozo Almonte"],
  "03": ["Antofagasta", "Mejillones", "Sierra Gorda", "Calama", "Ollagüe", "San Pedro de Atacama", "Tocopilla"],
  "04": ["Copiapó", "Caldera", "Tierra Amarilla", "Chañaral", "Diego de Almagro"],
  "05": [
    "La Serena",
    "Coquimbo",
    "Andacollo",
    "La Higuera",
    "Paiguano",
    "Ovalle",
    "Combarbalá",
    "Monte Patria",
    "Punitaqui",
    "Río Hurtado",
    "Illapel",
    "Canela",
    "Los Vilos",
    "Salamanca",
  ],
  "06": [
    "Valparaíso",
    "Casablanca",
    "Concón",
    "Juan Fernández",
    "Puchuncaví",
    "Quintero",
    "Viña del Mar",
    "La Calera",
    "Nogales",
    "Petorca",
    "Papudo",
    "Zapallar",
    "Quillota",
    "La Cruz",
    "Limache",
    "Olmué",
    "San Esteban",
    "San Felipe",
    "Santa María",
    "Putaendo",
    "Calle Larga",
    "San Isidro",
    "Catemu",
    "Llay-Llay",
    "Los Andes",
    "Carro",
    "Rinconada",
    "San Clemente",
    "Panquehue",
  ],
  "07": [
    "Rancagua",
    "Acopiaco",
    "Apalta",
    "Coltauco",
    "Doñihue",
    "Graneros",
    "Leyda",
    "Machalí",
    "Malloa",
    "Mostazal",
    "Olivar",
    "Peumo",
    "Pichidegua",
    "Quinta de Tilcoco",
    "Rengo",
    "Requínoa",
    "San Fernando",
    "San Vicente de Tagua Tagua",
    "Santa Cruz",
  ],
  "08": [
    "Talca",
    "Constitución",
    "Empedrado",
    "Maule",
    "Pencahue",
    "Pelarco",
    "Río Claro",
    "San Clemente",
    "San Javier",
    "Cauquenes",
    "Chanco",
    "Pelluhue",
    "Arauco",
    "Cabrero",
    "Laja",
    "Los Ángeles",
    "Mulchén",
    "Santa Bárbara",
    "Tomé",
    "Cobquecura",
    "Ninhue",
    "Ñiquén",
    "San Carlos",
    "San Fabián",
    "San Ignacio",
    "San Nicolás",
    "Treguaco",
    "Yungay",
  ],
  "09": [
    "Chillán",
    "Bulnes",
    "Chillán Viejo",
    "El Carmen",
    "Pemuco",
    "Pinto",
    "Quillón",
    "San Ignacio",
    "Yungay",
    "Coihueco",
    "Ninhue",
    "Ñiquén",
    "San Nicolás",
    "Treguaco",
  ],
  "10": [
    "Puerto Montt",
    "Ancud",
    "Castro",
    "Dalcahue",
    "Puqueldón",
    "Quemchi",
    "Quellón",
    "Calbuco",
    "Cochamó",
    "Fresia",
    "Frutillar",
    "Llanquihue",
    "Los Muermos",
    "Maullín",
    "Pargua",
    "Puerto Varas",
    "Osorno",
    "Purranque",
    "Puyehue",
    "Río Negro",
    "San Juan de la Costa",
    "San Pablo",
    "Chonchi",
    "Curaco de Vélez",
    "Quelicura",
  ],
  "11": ["Coyhaique", "Lago Verde", "Aysén", "Cisnes", "Guaitecas"],
  "12": ["Punta Arenas", "Laguna Blanca", "Río Verde", "Puerto Natales", "Porvenir", "Primavera", "Timaukel"],
  "13": [
    "Santiago",
    "Puente Alto",
    "Pirque",
    "San José de Maipo",
    "Buin",
    "Paine",
    "San Bernardo",
    "Calera de Tango",
    "Melipilla",
    "Alhué",
    "Curacaví",
    "María Pinto",
    "Peñaflor",
    "San Pedro",
    "Talagante",
    "El Monte",
    "Isla de Maipo",
    "Padre Hurtado",
    "Renca",
    "Cerrillos",
    "Estación Central",
    "Maipú",
    "Pudahuel",
    "Quilicura",
    "Quinta Normal",
    "Conchali",
    "Huechuraba",
    "Independencia",
    "La Cisterna",
    "La Granja",
    "La Florida",
    "La Pintana",
    "La Reina",
    "Las Condes",
    "Lo Barnechea",
    "Ñuñoa",
    "Providencia",
    "San Miguel",
    "San Ramón",
    "Vitacura",
    "Lampa",
    "Colina",
    "Tiltil",
  ],
  "14": [
    "Valdivia",
    "Corral",
    "Lachon",
    "Mariquina",
    "Máfil",
    "Panguipulli",
    "Futrono",
    "La Unión",
    "Lago Ranco",
    "Riñihue",
    "Los Lagos",
  ],
  "15": ["Atacama", "Chañaral", "Diego de Almagro"],
}

export type Region = (typeof REGIONS)[number]
export type Commune = string
