create table if not exists public.valuation_watchlist_alerts (
  id uuid primary key default gen_random_uuid(),
  watchlist_id uuid not null references public.valuation_watchlist(id) on delete cascade,
  alert_type text not null,
  severity text not null default 'info',
  title text not null,
  detail text,
  previous_value numeric,
  current_value numeric,
  metadata jsonb not null default '{}'::jsonb,
  acknowledged boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists valuation_watchlist_alerts_watchlist_idx on public.valuation_watchlist_alerts(watchlist_id, created_at desc);
create index if not exists valuation_watchlist_alerts_open_idx on public.valuation_watchlist_alerts(acknowledged, created_at desc);
alter table public.valuation_watchlist_alerts enable row level security;
comment on table public.valuation_watchlist_alerts is 'Internal SR alerts generated by repeated watchlist valuation checks.';